// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cards struct {
	Front string `json:"front"`
	Back  string `json:"back"`
}

type Comment struct {
	ID      string `json:"id"`
	UserID  string `json:"userId"`
	Comment string `json:"comment"`
}

type CommentInput struct {
	ID      string `json:"id"`
	UserID  string `json:"userId"`
	Comment string `json:"comment"`
}

type Deck struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	UserID      string   `json:"userId"`
	DateCreated string   `json:"dateCreated"`
	LastUpdate  string   `json:"lastUpdate"`
	Flashcards  []*Cards `json:"flashcards,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
